[build]
  publish = "."

[[redirects]]
  from = "/exterior/"
  to = "/categories/exterior/index.html"
  status = 200

[[redirects]]
  from = "/exterior"
  to = "/categories/exterior/index.html"
  status = 200

[[redirects]]
  from = "/interior/"
  to = "/categories/interior/index.html"
  status = 200

[[redirects]]
  from = "/interior"
  to = "/categories/interior/index.html"
  status = 200

[[redirects]]
  from = "/3d-rendering/"
  to = "/categories/3d-rendering/index.html"
  status = 200

[[redirects]]
  from = "/3d-rendering"
  to = "/categories/3d-rendering/index.html"
  status = 200

[[redirects]]
  from = "/3d-animation/"
  to = "/categories/3d-animation/index.html"
  status = 200

[[redirects]]
  from = "/3d-animation"
  to = "/categories/3d-animation/index.html"
  status = 200